POST http://localhost:8000/ HTTP/1.1
content-type: application/json
X-GitHub-Event: push

{
  "ref": "refs/heads/prod",
  "repository": {
    "full_name": "carmon/til",
    "default_branch": "main"
  },
  "installation": {
    "id": 15869060
  },
  "head_commit": {
    "added": [
      "blog/posts/test.md",
      "config.json"
    ]
  }
}